<!DOCTYPE html>
<html>
<head>
    <title>PHP Text Sample</title>
</head>
<body>

<?php
// PHP code starts here

// Define some text
$text = "Hello, this is a sample text generated by PHP!";

// Output the text
echo "<h1>$text</h1>";

// PHP code ends here
?>

</body>
</html>
